"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { engineDefinition } from "@/lib/exercise-engine-v2";

type ExerciseState = {
  kind?: string; visit?: number; score?: number; target?: string; targetIndex?: number; dartsThrown?: number; hits?: number;
  startedAt?: number; deadlineAt?: number; completionMode?: string; completionValue?: number; baseTarget?: number;
  attemptDarts?: number; highestTarget?: number; successes?: number; attempts?: number; engineConfig?: Record<string, unknown>;
  marks?: Record<string, number>; lives?: number; phase?: string; opened?: boolean;
};

type Props = { resultType: string; exerciseName: string; completionMode?: string | null; completionValue?: number | null; state?: ExerciseState | null; disabled?: boolean; onSubmit: (value: Record<string, unknown>) => Promise<void> | void };

function formatTime(totalSeconds: number) { const seconds = Math.max(0, totalSeconds); return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export default function ExerciseResultInput({ resultType, exerciseName, completionMode: configuredMode, completionValue: configuredValue, state, disabled = false, onSubmit }: Props) {
  const [score, setScore] = useState("");
  const [single, setSingle] = useState(0); const [double, setDouble] = useState(0); const [triple, setTriple] = useState(0);
  const [checkout, setCheckout] = useState(false); const [checkoutType, setCheckoutType] = useState("NONE"); const [doubleIn, setDoubleIn] = useState(false); const [dartsUsed, setDartsUsed] = useState(1);
  const [target, setTarget] = useState(""); const [marks, setMarks] = useState(0); const [points, setPoints] = useState(0); const [now, setNow] = useState(() => Date.now());
  const timeoutSent = useRef(false);
  const kind = state?.kind ?? "CUSTOM"; const config = state?.engineConfig ?? {}; const definition = engineDefinition(kind, config);
  const completionMode = configuredMode ?? state?.completionMode ?? "ENGINE_DEFAULT"; const completionValue = configuredValue ?? state?.completionValue ?? null;
  const remainingSeconds = useMemo(() => completionMode === "TIME_LIMIT" && state?.deadlineAt ? Math.max(0, Math.ceil((state.deadlineAt - now) / 1000)) : null, [completionMode, state?.deadlineAt, now]);
  const usedDarts = single + double + triple;

  useEffect(() => { timeoutSent.current = false; }, [state?.deadlineAt, state?.visit]);
  useEffect(() => { setDartsUsed(1); setScore(""); setSingle(0); setDouble(0); setTriple(0); setCheckout(false); setCheckoutType("NONE"); }, [state?.visit, state?.target]);
  useEffect(() => { if (completionMode !== "TIME_LIMIT" || !state?.deadlineAt) return; const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [completionMode, state?.deadlineAt]);
  useEffect(() => { if (remainingSeconds !== 0 || timeoutSent.current || disabled) return; timeoutSent.current = true; void onSubmit({ timedOut: true, finish: true }); }, [remainingSeconds, disabled, onSubmit]);

  async function submitScore(extra: Record<string, unknown> = {}) { if (score === "") return; await onSubmit({ score: Number(score), ...extra }); }
  async function submitSegments() { if (usedDarts > definition.dartsPerVisit) return; await onSubmit({ single, double, triple, hits: usedDarts }); }

  const usedVisits = Math.max(0, (state?.visit ?? 1) - 1); const limitCurrent = completionMode === "VISIT_LIMIT" ? usedVisits : completionMode === "DART_LIMIT" ? state?.dartsThrown ?? 0 : null;
  const limitPanel = (completionMode === "TIME_LIMIT" || limitCurrent != null) && completionValue ? <div className="competition-limit"><div className="competition-limit-copy"><small>{completionMode === "TIME_LIMIT" ? "Verbleibende Zeit" : completionMode === "DART_LIMIT" ? "Darts" : "Aufnahmen"}</small><strong>{completionMode === "TIME_LIMIT" ? formatTime(remainingSeconds ?? completionValue * 60) : `${limitCurrent} / ${completionValue}`}</strong></div></div> : null;

  const segmentInput = <><div className="segment-entry">{[["Single", single, setSingle], ["Doppel", double, setDouble], ["Treble", triple, setTriple]].map(([label, value, setter]) => <label key={String(label)}><span>{label}</span><input type="number" min="0" max={definition.dartsPerVisit} inputMode="numeric" value={Number(value)} onChange={(event) => (setter as (value: number) => void)(Math.max(0, Math.min(definition.dartsPerVisit, Number(event.target.value))))} /></label>)}</div><div className={`engine-dart-balance ${usedDarts > definition.dartsPerVisit ? "is-error" : ""}`}><span>Erfasste Darts</span><strong>{usedDarts} / {definition.dartsPerVisit}</strong></div><button className="button full engine-submit" disabled={disabled || usedDarts > definition.dartsPerVisit} onClick={() => void submitSegments()}>Aufnahme speichern</button></>;

  if (definition.inputMode === "HITS") return <div className="competition-engine competition-engine-hits">{limitPanel}<EngineHeader title={`Treffer auf ${state?.target ?? "das aktuelle Ziel"}`} state={state}/><div className="engine-hit-grid">{Array.from({ length: definition.dartsPerVisit + 1 }, (_, hits) => <button type="button" disabled={disabled} key={hits} onClick={() => void onSubmit({ hits })}><strong>{hits}</strong><span>Treffer</span></button>)}</div></div>;

  if (definition.inputMode === "SEGMENTS") return <div className="competition-engine competition-engine-segments">{limitPanel}<EngineHeader title={`Treffer auf ${state?.target ?? "das aktuelle Ziel"}`} state={state}/>{segmentInput}</div>;

  if (definition.inputMode === "X01") { const inRule = String(config.inRule ?? "SINGLE"); const outRule = String(config.outRule ?? "DOUBLE"); const displayScore = state?.score ?? Number(config.startScore ?? 501); return <div className="competition-engine competition-engine-score">{limitPanel}<EngineHeader title={`${displayScore} Rest · ${outRule} Out`} state={state}/><ScoreField score={score} setScore={setScore}/>{inRule === "DOUBLE" && !state?.opened && <button type="button" disabled={disabled} className={`engine-checkout-toggle ${doubleIn ? "is-active" : ""}`} onClick={() => setDoubleIn(!doubleIn)}>Mit Doppel eröffnet</button>}<div className="engine-segmented"><button type="button" disabled={disabled} className={checkoutType === "NONE" ? "is-active" : ""} onClick={() => setCheckoutType("NONE")}>Kein Checkout</button>{outRule === "SINGLE" && <button type="button" disabled={disabled} className={checkoutType === "SINGLE" ? "is-active" : ""} onClick={() => setCheckoutType("SINGLE")}>Single Out</button>}<button type="button" disabled={disabled} className={checkoutType === "DOUBLE" ? "is-active" : ""} onClick={() => setCheckoutType("DOUBLE")}>Double Out</button>{outRule === "MASTER" && <button type="button" disabled={disabled} className={checkoutType === "TREBLE" ? "is-active" : ""} onClick={() => setCheckoutType("TREBLE")}>Treble Out</button>}</div><button className="button full" disabled={disabled || score === ""} onClick={() => void submitScore({ checkout: checkoutType !== "NONE", checkoutType, doubleIn })}>Aufnahme speichern</button></div>; }

  if (definition.inputMode === "CHECKOUT") { const maxDarts = definition.maxDarts ?? 3; return <div className="competition-engine competition-engine-121">{limitPanel}<EngineHeader title={`Checkout ${state?.target ?? "–"}`} state={state}/><div className="game121-status"><div><small>Aktuelles Finish</small><strong>{state?.target ?? "–"}</strong></div><div><small>Darts im Versuch</small><strong>{state?.attemptDarts ?? 0} / {maxDarts}</strong></div><div><small>Erfolge</small><strong>{state?.successes ?? 0}</strong></div></div>{kind === "GAME_121" && <ScoreField score={score} setScore={setScore}/>}<CheckoutButtons checkout={checkout} setCheckout={setCheckout} disabled={disabled}/><DartsButtons value={dartsUsed} setValue={setDartsUsed} max={maxDarts} disabled={disabled}/><button className="button full" disabled={disabled || (kind === "GAME_121" && score === "")} onClick={() => void (kind === "GAME_121" ? submitScore({ checkout, dartsUsed }) : onSubmit({ checkout, dartsUsed }))}>Versuch speichern</button></div>; }

  if (definition.inputMode === "CRICKET") { const targets = Array.isArray(config.targets) ? config.targets : [15,16,17,18,19,20,"BULL"]; return <div className="competition-engine competition-engine-custom">{limitPanel}<EngineHeader title="Cricket" state={state}/><label>Ziel<select disabled={disabled} value={target || String(state?.target ?? targets[0])} onChange={(event) => setTarget(event.target.value)}>{targets.map((item) => <option key={String(item)}>{String(item)}</option>)}</select></label><div className="engine-hit-grid">{[0,1,2,3].map((value) => <button type="button" disabled={disabled} key={value} className={marks === value ? "is-active" : ""} onClick={() => setMarks(value)}><strong>{value}</strong><span>Marken</span></button>)}</div><label>Zusatzpunkte<input disabled={disabled} type="number" min="0" value={points} onChange={(event) => setPoints(Number(event.target.value))}/></label><button className="button full" disabled={disabled} onClick={() => void onSubmit({ target: target || state?.target, marks, points })}>Aufnahme speichern</button><button className="button secondary full" disabled={disabled} onClick={() => void onSubmit({ finish: true })}>Cricket abschließen</button></div>; }

  if (definition.inputMode === "KILLER") { const displayLives = state?.lives ?? Number(config.startLives ?? 3); return <div className="competition-engine competition-engine-custom"><EngineHeader title={`Killer · ${displayLives} Leben`} state={state}/><div className="engine-hit-grid">{[-3,-2,-1,0,1].map((value) => <button type="button" disabled={disabled} key={value} onClick={() => void onSubmit({ livesDelta: value })}><strong>{value > 0 ? `+${value}` : value}</strong><span>Leben</span></button>)}</div><button className="button secondary full" disabled={disabled} onClick={() => void onSubmit({ killer: true, livesDelta: 0 })}>Killerstatus aktivieren</button><button className="button danger-outline full" disabled={disabled} onClick={() => void onSubmit({ finish: true, livesDelta: 0 })}>Spiel abschließen</button></div>; }

  if (definition.inputMode === "BOARD_GAME") { const targets = Array.isArray(config.targets) ? config.targets : []; return <div className="competition-engine competition-engine-custom"><EngineHeader title={exerciseName} state={state}/><div className="score-quick-grid">{targets.map((item) => <button type="button" disabled={disabled} key={String(item)} onClick={() => void onSubmit({ target: String(item) })}>{String(item)}</button>)}</div><button className="button secondary full" disabled={disabled} onClick={() => void onSubmit({ finish: true })}>Spiel abschließen</button></div>; }

  if (definition.inputMode === "SCORE" || resultType === "SCORE_0_TO_180") return <div className="competition-engine competition-engine-score">{limitPanel}<EngineHeader title="Score dieser Aufnahme" state={state}/><ScoreField score={score} setScore={setScore}/><button className="button full" disabled={disabled || score === ""} onClick={() => void submitScore()}>Aufnahme speichern</button></div>;

  return <div className="competition-engine competition-engine-custom">{limitPanel}<EngineHeader title={`${exerciseName} · Ergebnis`} state={state}/><ScoreField score={score} setScore={setScore}/><div className="engine-custom-actions"><button className="button" disabled={disabled || score === ""} onClick={() => void submitScore()}>Speichern</button><button className="button secondary" disabled={disabled} onClick={() => void onSubmit({ value: score === "" ? 0 : Number(score), finish: true })}>Übung abschließen</button></div></div>;
}

function EngineHeader({ title, state }: { title: string; state?: ExerciseState | null }) { return <div className="engine-v2-header"><div className="engine-kicker">{title}</div><div className="engine-v2-meta"><span>Aufnahme {state?.visit ?? 1}</span>{state?.dartsThrown != null && <span>{state.dartsThrown} Darts</span>}{state?.score != null && <span>{state.score} Punkte</span>}</div></div>; }
function ScoreField({ score, setScore }: { score: string; setScore: (value: string) => void }) { return <div className="engine-score-entry"><label>Score<input type="number" inputMode="numeric" min="0" max="180" value={score} onChange={(event) => setScore(event.target.value)} placeholder="0–180" /></label></div>; }
function CheckoutButtons({ checkout, setCheckout, disabled }: { checkout: boolean; setCheckout: (value: boolean) => void; disabled: boolean }) { return <div className="engine-segmented"><button type="button" disabled={disabled} className={!checkout ? "is-active" : ""} onClick={() => setCheckout(false)}>Nicht gecheckt</button><button type="button" disabled={disabled} className={checkout ? "is-active is-success" : ""} onClick={() => setCheckout(true)}>Checkout geschafft</button></div>; }
function DartsButtons({ value, setValue, max, disabled }: { value: number; setValue: (value: number) => void; max: number; disabled: boolean }) { return <div className="engine-darts-select"><small>Verwendete Darts</small><div>{Array.from({ length: max }, (_, index) => index + 1).map((item) => <button type="button" disabled={disabled} className={value === item ? "is-active" : ""} key={item} onClick={() => setValue(item)}>{item}</button>)}</div></div>; }
