"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type ExerciseState = {
  kind?: string; visit?: number; score?: number; target?: string; targetIndex?: number; dartsThrown?: number; hits?: number;
  startedAt?: number; deadlineAt?: number; completionMode?: string; completionValue?: number; baseTarget?: number;
  attemptDarts?: number; highestTarget?: number; successes?: number; engineConfig?: Record<string, unknown>;
  marks?: Record<string, number>; lives?: number; phase?: string; opened?: boolean;
};

type Props = { resultType: string; exerciseName: string; completionMode?: string | null; completionValue?: number | null; state?: ExerciseState | null; disabled?: boolean; onSubmit: (value: Record<string, unknown>) => Promise<void> | void };

function formatTime(totalSeconds: number) { const seconds = Math.max(0, totalSeconds); return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export default function ExerciseResultInput({ resultType, exerciseName, completionMode: configuredMode, completionValue: configuredValue, state, disabled = false, onSubmit }: Props) {
  const [score, setScore] = useState(""); const [single, setSingle] = useState("0"); const [double, setDouble] = useState("0"); const [triple, setTriple] = useState("0");
  const [checkout, setCheckout] = useState(false); const [checkoutType, setCheckoutType] = useState("NONE"); const [doubleIn, setDoubleIn] = useState(false); const [dartsUsed, setDartsUsed] = useState(3);
  const [target, setTarget] = useState(""); const [marks, setMarks] = useState(0); const [points, setPoints] = useState(0); const [now, setNow] = useState(() => Date.now());
  const timeoutSent = useRef(false); const kind = state?.kind ?? "CUSTOM"; const config = state?.engineConfig ?? {};
  const completionMode = configuredMode ?? state?.completionMode ?? "ENGINE_DEFAULT"; const completionValue = configuredValue ?? state?.completionValue ?? null;
  const remainingSeconds = useMemo(() => completionMode === "TIME_LIMIT" && state?.deadlineAt ? Math.max(0, Math.ceil((state.deadlineAt - now) / 1000)) : null, [completionMode, state?.deadlineAt, now]);
  useEffect(() => { timeoutSent.current = false; }, [state?.deadlineAt, state?.visit]);
  useEffect(() => { if (completionMode !== "TIME_LIMIT" || !state?.deadlineAt) return; const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [completionMode, state?.deadlineAt]);
  useEffect(() => { if (remainingSeconds !== 0 || timeoutSent.current || disabled) return; timeoutSent.current = true; void onSubmit({ timedOut: true, finish: true }); }, [remainingSeconds, disabled, onSubmit]);

  async function submitScore(extra: Record<string, unknown> = {}) { if (score === "") return; await onSubmit({ score: Number(score), ...extra }); setScore(""); setCheckout(false); setCheckoutType("NONE"); setDoubleIn(false); setDartsUsed(3); }
  async function submitSegments() { await onSubmit({ single: Number(single), double: Number(double), triple: Number(triple), hits: Number(single) + Number(double) + Number(triple) }); setSingle("0"); setDouble("0"); setTriple("0"); }

  const usedVisits = Math.max(0, (state?.visit ?? 1) - 1); const limitCurrent = completionMode === "VISIT_LIMIT" ? usedVisits : completionMode === "DART_LIMIT" ? state?.dartsThrown ?? 0 : null;
  const limitPanel = (completionMode === "TIME_LIMIT" || limitCurrent != null) && completionValue ? <div className="competition-limit"><div className="competition-limit-copy"><small>{completionMode === "TIME_LIMIT" ? "Verbleibende Zeit" : completionMode === "DART_LIMIT" ? "Darts" : "Aufnahmen"}</small><strong>{completionMode === "TIME_LIMIT" ? formatTime(remainingSeconds ?? completionValue * 60) : `${limitCurrent} / ${completionValue}`}</strong></div></div> : null;
  const segmentInput = <><div className="segment-entry">{[{ label: "Single", value: single, set: setSingle }, { label: "Doppel", value: double, set: setDouble }, { label: "Treble", value: triple, set: setTriple }].map((item) => <label key={item.label}><span>{item.label}</span><input type="number" min="0" max="3" inputMode="numeric" value={item.value} onChange={(event) => item.set(event.target.value)} /></label>)}</div><button className="button full engine-submit" disabled={disabled} onClick={() => void submitSegments()}>Aufnahme speichern</button></>;

  if (kind === "GAME_121") return <div className="competition-engine competition-engine-121">{limitPanel}<div className="engine-kicker">121 · Checkout-Challenge</div><div className="game121-status"><div><small>Restscore</small><strong>{state?.score ?? state?.target ?? 121}</strong></div><div><small>Darts im Versuch</small><strong>{state?.attemptDarts ?? 0} / {Number(config.dartsPerAttempt ?? 9)}</strong></div><div><small>Gesichert</small><strong>{state?.baseTarget ?? 121}</strong></div></div><ScoreField score={score} setScore={setScore}/><CheckoutButtons checkout={checkout} setCheckout={setCheckout}/><DartsButtons value={dartsUsed} setValue={setDartsUsed} max={3}/><button className="button full" disabled={disabled || score === ""} onClick={() => void submitScore({ checkout, dartsUsed })}>Aufnahme speichern</button></div>;

  if (kind === "BOB27" || kind === "BOB27_CONFIGURED" || kind.startsWith("AROUND_") || ["DOUBLES_ROUNDS", "BULL_ROUNDS", "HIT_ROUNDS", "HIT_TARGET"].includes(kind)) return <div className="competition-engine competition-engine-hits">{limitPanel}<div className="engine-kicker">Treffer auf {state?.target ?? "das aktuelle Ziel"}</div><div className="engine-hit-grid">{[0,1,2,3].map((hits) => <button disabled={disabled} key={hits} onClick={() => void onSubmit({ hits })}><strong>{hits}</strong><span>Treffer</span></button>)}</div></div>;

  if (["SHANGHAI", "SHANGHAI_CONFIGURED", "SEGMENT_POINTS", "SWITCH", "BASEBALL", "TARGET_SEQUENCE", "HALVE_IT"].includes(kind)) return <div className="competition-engine competition-engine-segments">{limitPanel}<div className="engine-kicker">Treffer auf {state?.target ?? "das aktuelle Ziel"}</div>{segmentInput}</div>;

  if (kind === "X01" || kind === "X01_CONFIGURED") { const inRule = String(config.inRule ?? "SINGLE"); const outRule = String(config.outRule ?? "DOUBLE"); const configuredStartScore = Number(config.startScore ?? 501); const displayScore = state?.score ?? (Number.isFinite(configuredStartScore) ? configuredStartScore : 501); return <div className="competition-engine competition-engine-score">{limitPanel}<div className="engine-kicker">{displayScore} Rest · {outRule} Out</div><ScoreField score={score} setScore={setScore}/>{inRule === "DOUBLE" && !state?.opened && <button type="button" className={`engine-checkout-toggle ${doubleIn ? "is-active" : ""}`} onClick={() => setDoubleIn(!doubleIn)}>Mit Doppel eröffnet</button>}<div className="engine-segmented"><button type="button" className={checkoutType === "NONE" ? "is-active" : ""} onClick={() => setCheckoutType("NONE")}>Kein Checkout</button><button type="button" className={checkoutType === "DOUBLE" ? "is-active" : ""} onClick={() => setCheckoutType("DOUBLE")}>Double Out</button>{outRule === "MASTER" && <button type="button" className={checkoutType === "TREBLE" ? "is-active" : ""} onClick={() => setCheckoutType("TREBLE")}>Treble Out</button>}</div><button className="button full" disabled={disabled || score === ""} onClick={() => void submitScore({ checkout: checkoutType !== "NONE", checkoutType, doubleIn })}>Aufnahme speichern</button></div>; }

  if (["CHECKOUT_RANGE", "FIXED_CHECKOUT", "RANDOM_CHECKOUT"].includes(kind)) return <div className="competition-engine competition-engine-121">{limitPanel}<div className="engine-kicker">Checkout {state?.target}</div><div className="game121-status"><div><small>Aktuelles Finish</small><strong>{state?.target ?? "–"}</strong></div><div><small>Darts im Versuch</small><strong>{state?.attemptDarts ?? 0}</strong></div><div><small>Erfolge</small><strong>{state?.successes ?? 0}</strong></div></div><CheckoutButtons checkout={checkout} setCheckout={setCheckout}/><DartsButtons value={dartsUsed} setValue={setDartsUsed} max={3}/><button className="button full" disabled={disabled} onClick={() => void onSubmit({ checkout, dartsUsed })}>Versuch speichern</button></div>;

  if (kind === "CRICKET") { const targets = Array.isArray(config.targets) ? config.targets : [15,16,17,18,19,20,"BULL"]; return <div className="competition-engine competition-engine-custom">{limitPanel}<div className="engine-kicker">Cricket-Marken</div><label>Ziel<select value={target || String(state?.target ?? targets[0])} onChange={(event) => setTarget(event.target.value)}>{targets.map((item) => <option key={String(item)}>{String(item)}</option>)}</select></label><div className="engine-hit-grid">{[0,1,2,3].map((value) => <button key={value} className={marks === value ? "is-active" : ""} onClick={() => setMarks(value)}><strong>{value}</strong><span>Marken</span></button>)}</div><label>Zusatzpunkte<input type="number" value={points} onChange={(event) => setPoints(Number(event.target.value))}/></label><button className="button full" onClick={() => void onSubmit({ target: target || state?.target, marks, points })}>Speichern</button><button className="button secondary full" onClick={() => void onSubmit({ finish: true })}>Cricket abschließen</button></div>; }

  if (kind === "KILLER") { const configuredLives = Number(config.startLives ?? 3); const displayLives = state?.lives ?? (Number.isFinite(configuredLives) ? configuredLives : 3); return <div className="competition-engine competition-engine-custom"><div className="engine-kicker">Killer · {displayLives} Leben</div><div className="engine-hit-grid">{[-3,-2,-1,0,1].map((value) => <button key={value} onClick={() => void onSubmit({ livesDelta: value })}><strong>{value > 0 ? `+${value}` : value}</strong><span>Leben</span></button>)}</div><button className="button secondary full" onClick={() => void onSubmit({ killer: true, livesDelta: 0 })}>Killerstatus aktivieren</button></div>; }

  if (kind === "TIC_TAC_TOE") { const targets = Array.isArray(config.targets) ? config.targets : []; return <div className="competition-engine competition-engine-custom"><div className="engine-kicker">Tic Tac Toe</div><div className="score-quick-grid">{targets.map((item) => <button key={String(item)} onClick={() => void onSubmit({ target: String(item) })}>{String(item)}</button>)}</div><button className="button secondary full" onClick={() => void onSubmit({ finish: true })}>Spiel abschließen</button></div>; }

  if (["SCORING", "FIVES", "COUNT_UP"].includes(kind) || resultType === "SCORE_0_TO_180") return <div className="competition-engine competition-engine-score">{limitPanel}<div className="engine-kicker">Score dieser Aufnahme</div><ScoreField score={score} setScore={setScore}/><button className="button full" disabled={disabled || score === ""} onClick={() => void submitScore()}>Aufnahme speichern</button></div>;

  return <div className="competition-engine competition-engine-custom">{limitPanel}<div className="engine-kicker">{exerciseName} · Ergebnis dieser Aufnahme</div><ScoreField score={score} setScore={setScore}/><div className="engine-custom-actions"><button className="button" disabled={disabled || score === ""} onClick={() => void submitScore()}>Speichern</button><button className="button secondary" onClick={() => void onSubmit({ value: score === "" ? 0 : Number(score), finish: true })}>Übung abschließen</button></div></div>;
}

function ScoreField({ score, setScore }: { score: string; setScore: (value: string) => void }) { return <div className="engine-score-entry"><label>Score<input type="number" inputMode="numeric" min="0" max="180" value={score} onChange={(event) => setScore(event.target.value)} placeholder="0–180" /></label></div>; }
function CheckoutButtons({ checkout, setCheckout }: { checkout: boolean; setCheckout: (value: boolean) => void }) { return <div className="engine-segmented"><button type="button" className={!checkout ? "is-active" : ""} onClick={() => setCheckout(false)}>Nicht gecheckt</button><button type="button" className={checkout ? "is-active is-success" : ""} onClick={() => setCheckout(true)}>Checkout geschafft</button></div>; }
function DartsButtons({ value, setValue, max }: { value: number; setValue: (value: number) => void; max: number }) { return <div className="engine-darts-select"><small>Verwendete Darts</small><div>{Array.from({ length: max }, (_, index) => index + 1).map((item) => <button type="button" className={value === item ? "is-active" : ""} key={item} onClick={() => setValue(item)}>{item}</button>)}</div></div>; }